services:
  - type: web
    name: fluide-app
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: false
    preDeployCommand: npm run db:push
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fluide-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: ISSUER_URL
        value: https://replit.com/oidc
      # Ces variables doivent être ajoutées manuellement dans l'interface Render
      # REPL_ID=e294c174-77ca-4f4d-8c4d-9f64219dae0e
      # REPL_OWNER=jeanfrancoisfer  
      # REPLIT_DOMAINS=votre-app.onrender.com

databases:
  - name: fluide-db
    plan: free
    databaseName: fluide
    user: fluide_user