#!/bin/bash

echo "=== Variables d'environnement pour déploiement Render ==="
echo ""
echo "Variables obligatoires à copier dans Render :"
echo ""
echo "NODE_ENV=production"
echo "REPL_ID=$REPL_ID"
echo "REPL_OWNER=$REPL_OWNER"
echo "REPLIT_DOMAINS=fluidemeet.onrender.com"
echo "ISSUER_URL=https://replit.com/oidc"
echo "SESSION_SECRET=taCleSecretePourSession"
echo ""
echo "Variables optionnelles (si vous utilisez ces services) :"
echo "ANTHROPIC_API_KEY=votre-cle-anthropic"
echo "SENDGRID_API_KEY=votre-cle-sendgrid"
echo "STRIPE_SECRET_KEY=votre-cle-stripe"
echo "VITE_STRIPE_PUBLIC_KEY=votre-cle-publique-stripe"
echo ""
echo "=== Render créera automatiquement ==="
echo "DATABASE_URL (nouvelle base PostgreSQL)"
echo "PORT (assigné par Render)"