#!/bin/bash

echo "🔍 TOUTES LES VARIABLES D'ENVIRONNEMENT - PROJET FLUIDE"
echo "========================================================="
echo ""

echo "📋 VARIABLES PRINCIPALES :"
echo "--------------------------"
echo "REPL_ID: $REPL_ID"
echo "REPL_OWNER: $REPL_OWNER"
echo "REPL_SLUG: $REPL_SLUG"
echo ""

echo "🗄️ BASE DE DONNÉES :"
echo "---------------------"
echo "DATABASE_URL: $DATABASE_URL"
echo "PGHOST: $PGHOST"
echo "PGUSER: $PGUSER"
echo "PGDATABASE: $PGDATABASE"
echo "PGPORT: $PGPORT"
echo ""

echo "🔐 SÉCURITÉ :"
echo "--------------"
echo "SESSION_SECRET: ${SESSION_SECRET:0:20}..." 
echo "ISSUER_URL: $ISSUER_URL"
echo ""

echo "🌐 DOMAINES :"
echo "--------------"
echo "REPLIT_DOMAINS: $REPLIT_DOMAINS"
echo "REPLIT_DEV_DOMAIN: $REPLIT_DEV_DOMAIN"
echo ""

echo "⚙️ CONFIGURATION :"
echo "-------------------"
echo "NODE_ENV: $NODE_ENV"
echo "PORT: $PORT"
echo "REPLIT_ENVIRONMENT: $REPLIT_ENVIRONMENT"
echo ""

echo "📊 API KEYS (si configurées) :"
echo "-------------------------------"
echo "ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:+[CONFIGURÉE]}"
echo "SENDGRID_API_KEY: ${SENDGRID_API_KEY:+[CONFIGURÉE]}"
echo "STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:+[CONFIGURÉE]}"
echo "VITE_STRIPE_PUBLIC_KEY: ${VITE_STRIPE_PUBLIC_KEY:+[CONFIGURÉE]}"
echo ""

echo "✅ RÉSUMÉ POUR RENDER :"
echo "========================"
echo "Variables à copier dans Render :"
echo ""
echo "NODE_ENV=production"
echo "REPL_ID=$REPL_ID"
echo "REPL_OWNER=$REPL_OWNER"
echo "REPLIT_DOMAINS=fluidemeet.onrender.com"
echo "ISSUER_URL=$ISSUER_URL"
echo "SESSION_SECRET=$SESSION_SECRET"